/* tslint:disable */
/* eslint-disable */
/**
 * Studio 3D API
 * API para la gestión de modelos 3D usando Meshy.ai. Permite convertir imágenes a modelos 3D y gestionar las tareas de generación.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface CreateImageTo3DDto
 */
export interface CreateImageTo3DDto {
    /**
     * URL pública de la imagen a convertir
     * @type {string}
     * @memberof CreateImageTo3DDto
     */
    'imageUrl'?: string;
    /**
     * Imagen codificada en base64 (data URI)
     * @type {string}
     * @memberof CreateImageTo3DDto
     */
    'imageBase64'?: string;
    /**
     * Tipo de modelo a generar
     * @type {string}
     * @memberof CreateImageTo3DDto
     */
    'modelType'?: CreateImageTo3DDtoModelTypeEnum;
    /**
     * Número objetivo de polígonos (1000-50000)
     * @type {number}
     * @memberof CreateImageTo3DDto
     */
    'targetPolycount'?: number;
    /**
     * Aplicar texturas al modelo
     * @type {boolean}
     * @memberof CreateImageTo3DDto
     */
    'shouldTexture'?: boolean;
    /**
     * Aplicar remallado al modelo
     * @type {boolean}
     * @memberof CreateImageTo3DDto
     */
    'shouldRemesh'?: boolean;
    /**
     * Aplicar simetría al modelo
     * @type {string}
     * @memberof CreateImageTo3DDto
     */
    'symmetry'?: CreateImageTo3DDtoSymmetryEnum;
    /**
     * Activar moderación de contenido
     * @type {boolean}
     * @memberof CreateImageTo3DDto
     */
    'moderation'?: boolean;
    /**
     * Nombre personalizado para la tarea/modelo
     * @type {string}
     * @memberof CreateImageTo3DDto
     */
    'name'?: string;
}

export const CreateImageTo3DDtoModelTypeEnum = {
    Standard: 'standard',
    Premium: 'premium'
} as const;

export type CreateImageTo3DDtoModelTypeEnum = typeof CreateImageTo3DDtoModelTypeEnum[keyof typeof CreateImageTo3DDtoModelTypeEnum];
export const CreateImageTo3DDtoSymmetryEnum = {
    None: 'none',
    X: 'x',
    Y: 'y',
    Z: 'z'
} as const;

export type CreateImageTo3DDtoSymmetryEnum = typeof CreateImageTo3DDtoSymmetryEnum[keyof typeof CreateImageTo3DDtoSymmetryEnum];

/**
 * 
 * @export
 * @interface CreateTaskResponseDto
 */
export interface CreateTaskResponseDto {
    /**
     * ID único de la tarea creada (UUID)
     * @type {string}
     * @memberof CreateTaskResponseDto
     */
    'taskId': string;
    /**
     * ID de la tarea en Meshy.ai
     * @type {string}
     * @memberof CreateTaskResponseDto
     */
    'meshyTaskId': string;
    /**
     * Estado inicial de la tarea
     * @type {string}
     * @memberof CreateTaskResponseDto
     */
    'status': CreateTaskResponseDtoStatusEnum;
    /**
     * Nombre personalizado de la tarea/modelo
     * @type {string}
     * @memberof CreateTaskResponseDto
     */
    'name'?: string;
    /**
     * Fecha de creación de la tarea
     * @type {string}
     * @memberof CreateTaskResponseDto
     */
    'createdAt': string;
}

export const CreateTaskResponseDtoStatusEnum = {
    Pending: 'PENDING',
    InProgress: 'IN_PROGRESS',
    Succeeded: 'SUCCEEDED',
    Failed: 'FAILED'
} as const;

export type CreateTaskResponseDtoStatusEnum = typeof CreateTaskResponseDtoStatusEnum[keyof typeof CreateTaskResponseDtoStatusEnum];

/**
 * 
 * @export
 * @interface DownloadModelResponseDto
 */
export interface DownloadModelResponseDto {
    /**
     * URL de descarga del modelo
     * @type {string}
     * @memberof DownloadModelResponseDto
     */
    'downloadUrl': string;
}
/**
 * 
 * @export
 * @interface MeshyControllerCreateImageTo3DTask400Response
 */
export interface MeshyControllerCreateImageTo3DTask400Response {
    /**
     * 
     * @type {number}
     * @memberof MeshyControllerCreateImageTo3DTask400Response
     */
    'statusCode'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof MeshyControllerCreateImageTo3DTask400Response
     */
    'message'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof MeshyControllerCreateImageTo3DTask400Response
     */
    'error'?: string;
}
/**
 * 
 * @export
 * @interface MeshyControllerDownloadModel400Response
 */
export interface MeshyControllerDownloadModel400Response {
    /**
     * 
     * @type {number}
     * @memberof MeshyControllerDownloadModel400Response
     */
    'statusCode'?: number;
    /**
     * 
     * @type {string}
     * @memberof MeshyControllerDownloadModel400Response
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof MeshyControllerDownloadModel400Response
     */
    'error'?: string;
}
/**
 * 
 * @export
 * @interface MeshyControllerDownloadModel404Response
 */
export interface MeshyControllerDownloadModel404Response {
    /**
     * 
     * @type {number}
     * @memberof MeshyControllerDownloadModel404Response
     */
    'statusCode'?: number;
    /**
     * 
     * @type {string}
     * @memberof MeshyControllerDownloadModel404Response
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof MeshyControllerDownloadModel404Response
     */
    'error'?: string;
}
/**
 * 
 * @export
 * @interface MeshyControllerGetTaskStatus404Response
 */
export interface MeshyControllerGetTaskStatus404Response {
    /**
     * 
     * @type {number}
     * @memberof MeshyControllerGetTaskStatus404Response
     */
    'statusCode'?: number;
    /**
     * 
     * @type {string}
     * @memberof MeshyControllerGetTaskStatus404Response
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof MeshyControllerGetTaskStatus404Response
     */
    'error'?: string;
}
/**
 * 
 * @export
 * @interface MeshyControllerGetTaskStatusFromMeshy400Response
 */
export interface MeshyControllerGetTaskStatusFromMeshy400Response {
    /**
     * 
     * @type {number}
     * @memberof MeshyControllerGetTaskStatusFromMeshy400Response
     */
    'statusCode'?: number;
    /**
     * 
     * @type {string}
     * @memberof MeshyControllerGetTaskStatusFromMeshy400Response
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof MeshyControllerGetTaskStatusFromMeshy400Response
     */
    'error'?: string;
}
/**
 * 
 * @export
 * @interface MeshyControllerGetTaskStatusFromMeshy404Response
 */
export interface MeshyControllerGetTaskStatusFromMeshy404Response {
    /**
     * 
     * @type {number}
     * @memberof MeshyControllerGetTaskStatusFromMeshy404Response
     */
    'statusCode'?: number;
    /**
     * 
     * @type {string}
     * @memberof MeshyControllerGetTaskStatusFromMeshy404Response
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof MeshyControllerGetTaskStatusFromMeshy404Response
     */
    'error'?: string;
}
/**
 * 
 * @export
 * @interface TaskStatusResponseDto
 */
export interface TaskStatusResponseDto {
    /**
     * ID único de la tarea (UUID)
     * @type {string}
     * @memberof TaskStatusResponseDto
     */
    'taskId': string;
    /**
     * ID de la tarea en Meshy.ai
     * @type {string}
     * @memberof TaskStatusResponseDto
     */
    'meshyTaskId': string;
    /**
     * Estado actual de la tarea
     * @type {string}
     * @memberof TaskStatusResponseDto
     */
    'status': TaskStatusResponseDtoStatusEnum;
    /**
     * Progreso de la tarea (0-100)
     * @type {number}
     * @memberof TaskStatusResponseDto
     */
    'progress'?: number;
    /**
     * URLs de los modelos generados en diferentes formatos
     * @type {object}
     * @memberof TaskStatusResponseDto
     */
    'modelUrls'?: object;
    /**
     * Mensaje de error si la tarea falló
     * @type {string}
     * @memberof TaskStatusResponseDto
     */
    'error'?: string;
    /**
     * Nombre personalizado de la tarea/modelo
     * @type {string}
     * @memberof TaskStatusResponseDto
     */
    'name'?: string;
    /**
     * Fecha de creación de la tarea
     * @type {string}
     * @memberof TaskStatusResponseDto
     */
    'createdAt': string;
    /**
     * Fecha de última actualización de la tarea
     * @type {string}
     * @memberof TaskStatusResponseDto
     */
    'updatedAt': string;
}

export const TaskStatusResponseDtoStatusEnum = {
    Pending: 'PENDING',
    InProgress: 'IN_PROGRESS',
    Succeeded: 'SUCCEEDED',
    Failed: 'FAILED'
} as const;

export type TaskStatusResponseDtoStatusEnum = typeof TaskStatusResponseDtoStatusEnum[keyof typeof TaskStatusResponseDtoStatusEnum];


/**
 * HealthApi - axios parameter creator
 * @export
 */
export const HealthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Endpoint básico para verificar que el servidor está funcionando
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerGetHello: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HealthApi - functional programming interface
 * @export
 */
export const HealthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HealthApiAxiosParamCreator(configuration)
    return {
        /**
         * Endpoint básico para verificar que el servidor está funcionando
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async appControllerGetHello(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.appControllerGetHello(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HealthApi.appControllerGetHello']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HealthApi - factory interface
 * @export
 */
export const HealthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HealthApiFp(configuration)
    return {
        /**
         * Endpoint básico para verificar que el servidor está funcionando
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerGetHello(options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.appControllerGetHello(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HealthApi - object-oriented interface
 * @export
 * @class HealthApi
 * @extends {BaseAPI}
 */
export class HealthApi extends BaseAPI {
    /**
     * Endpoint básico para verificar que el servidor está funcionando
     * @summary Health check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthApi
     */
    public appControllerGetHello(options?: RawAxiosRequestConfig) {
        return HealthApiFp(this.configuration).appControllerGetHello(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MeshyApi - axios parameter creator
 * @export
 */
export const MeshyApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Cancela una tarea de generación de modelo 3D. Marca la tarea como FAILED y detiene el procesamiento.
         * @summary Cancelar una tarea
         * @param {string} taskId ID único de la tarea (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meshyControllerCancelTask: async (taskId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'taskId' is not null or undefined
            assertParamExists('meshyControllerCancelTask', 'taskId', taskId)
            const localVarPath = `/meshy/task/{taskId}`
                .replace(`{${"taskId"}}`, encodeURIComponent(String(taskId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Inicia una nueva tarea para convertir una imagen en un modelo 3D usando Meshy.ai. Debes proporcionar una URL de imagen o una imagen en base64.
         * @summary Crear tarea de conversión de imagen a modelo 3D
         * @param {CreateImageTo3DDto} createImageTo3DDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meshyControllerCreateImageTo3DTask: async (createImageTo3DDto: CreateImageTo3DDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createImageTo3DDto' is not null or undefined
            assertParamExists('meshyControllerCreateImageTo3DTask', 'createImageTo3DDto', createImageTo3DDto)
            const localVarPath = `/meshy/image-to-3d`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createImageTo3DDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Obtiene la URL de descarga del modelo generado en el formato especificado. La tarea debe estar completada (status: SUCCEEDED).
         * @summary Obtener URL de descarga del modelo
         * @param {string} taskId ID único de la tarea (UUID)
         * @param {MeshyControllerDownloadModelFormatEnum} [format] Formato del modelo a descargar
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meshyControllerDownloadModel: async (taskId: string, format?: MeshyControllerDownloadModelFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'taskId' is not null or undefined
            assertParamExists('meshyControllerDownloadModel', 'taskId', taskId)
            const localVarPath = `/meshy/task/{taskId}/download`
                .replace(`{${"taskId"}}`, encodeURIComponent(String(taskId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Obtiene una lista de todas las tareas de generación de modelos 3D creadas.
         * @summary Listar todas las tareas
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meshyControllerGetAllTasks: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/meshy/tasks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Obtiene el estado actual de una tarea de generación de modelo 3D desde la base de datos local (actualizada desde Meshy). Incluye el progreso, URLs de los modelos generados y cualquier error.
         * @summary Consultar estado de una tarea
         * @param {string} taskId ID único de la tarea (UUID local)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meshyControllerGetTaskStatus: async (taskId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'taskId' is not null or undefined
            assertParamExists('meshyControllerGetTaskStatus', 'taskId', taskId)
            const localVarPath = `/meshy/task/{taskId}`
                .replace(`{${"taskId"}}`, encodeURIComponent(String(taskId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Obtiene el estado actual de una tarea directamente desde Meshy API, sin pasar por la base de datos local. Acepta tanto el taskId local (UUID) como el meshyTaskId (ID de Meshy). Si se proporciona un taskId local, se busca el meshyTaskId correspondiente en la BD.
         * @summary Consultar estado directamente desde Meshy
         * @param {string} taskIdOrMeshyId ID de la tarea local (UUID) o ID de Meshy. Si es un UUID local, se buscará el meshyTaskId correspondiente.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meshyControllerGetTaskStatusFromMeshy: async (taskIdOrMeshyId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'taskIdOrMeshyId' is not null or undefined
            assertParamExists('meshyControllerGetTaskStatusFromMeshy', 'taskIdOrMeshyId', taskIdOrMeshyId)
            const localVarPath = `/meshy/meshy-task/{taskIdOrMeshyId}`
                .replace(`{${"taskIdOrMeshyId"}}`, encodeURIComponent(String(taskIdOrMeshyId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Descarga el modelo desde Meshy a través del servidor para evitar problemas de CORS. Devuelve el archivo directamente.
         * @summary Descargar modelo a través del servidor (proxy)
         * @param {string} taskId ID único de la tarea (UUID)
         * @param {MeshyControllerProxyModelFormatEnum} [format] Formato del modelo a descargar
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meshyControllerProxyModel: async (taskId: string, format?: MeshyControllerProxyModelFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'taskId' is not null or undefined
            assertParamExists('meshyControllerProxyModel', 'taskId', taskId)
            const localVarPath = `/meshy/task/{taskId}/proxy`
                .replace(`{${"taskId"}}`, encodeURIComponent(String(taskId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MeshyApi - functional programming interface
 * @export
 */
export const MeshyApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MeshyApiAxiosParamCreator(configuration)
    return {
        /**
         * Cancela una tarea de generación de modelo 3D. Marca la tarea como FAILED y detiene el procesamiento.
         * @summary Cancelar una tarea
         * @param {string} taskId ID único de la tarea (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meshyControllerCancelTask(taskId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.meshyControllerCancelTask(taskId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MeshyApi.meshyControllerCancelTask']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Inicia una nueva tarea para convertir una imagen en un modelo 3D usando Meshy.ai. Debes proporcionar una URL de imagen o una imagen en base64.
         * @summary Crear tarea de conversión de imagen a modelo 3D
         * @param {CreateImageTo3DDto} createImageTo3DDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meshyControllerCreateImageTo3DTask(createImageTo3DDto: CreateImageTo3DDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateTaskResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.meshyControllerCreateImageTo3DTask(createImageTo3DDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MeshyApi.meshyControllerCreateImageTo3DTask']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Obtiene la URL de descarga del modelo generado en el formato especificado. La tarea debe estar completada (status: SUCCEEDED).
         * @summary Obtener URL de descarga del modelo
         * @param {string} taskId ID único de la tarea (UUID)
         * @param {MeshyControllerDownloadModelFormatEnum} [format] Formato del modelo a descargar
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meshyControllerDownloadModel(taskId: string, format?: MeshyControllerDownloadModelFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DownloadModelResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.meshyControllerDownloadModel(taskId, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MeshyApi.meshyControllerDownloadModel']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Obtiene una lista de todas las tareas de generación de modelos 3D creadas.
         * @summary Listar todas las tareas
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meshyControllerGetAllTasks(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TaskStatusResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.meshyControllerGetAllTasks(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MeshyApi.meshyControllerGetAllTasks']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Obtiene el estado actual de una tarea de generación de modelo 3D desde la base de datos local (actualizada desde Meshy). Incluye el progreso, URLs de los modelos generados y cualquier error.
         * @summary Consultar estado de una tarea
         * @param {string} taskId ID único de la tarea (UUID local)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meshyControllerGetTaskStatus(taskId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaskStatusResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.meshyControllerGetTaskStatus(taskId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MeshyApi.meshyControllerGetTaskStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Obtiene el estado actual de una tarea directamente desde Meshy API, sin pasar por la base de datos local. Acepta tanto el taskId local (UUID) como el meshyTaskId (ID de Meshy). Si se proporciona un taskId local, se busca el meshyTaskId correspondiente en la BD.
         * @summary Consultar estado directamente desde Meshy
         * @param {string} taskIdOrMeshyId ID de la tarea local (UUID) o ID de Meshy. Si es un UUID local, se buscará el meshyTaskId correspondiente.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meshyControllerGetTaskStatusFromMeshy(taskIdOrMeshyId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaskStatusResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.meshyControllerGetTaskStatusFromMeshy(taskIdOrMeshyId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MeshyApi.meshyControllerGetTaskStatusFromMeshy']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Descarga el modelo desde Meshy a través del servidor para evitar problemas de CORS. Devuelve el archivo directamente.
         * @summary Descargar modelo a través del servidor (proxy)
         * @param {string} taskId ID único de la tarea (UUID)
         * @param {MeshyControllerProxyModelFormatEnum} [format] Formato del modelo a descargar
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meshyControllerProxyModel(taskId: string, format?: MeshyControllerProxyModelFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.meshyControllerProxyModel(taskId, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MeshyApi.meshyControllerProxyModel']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MeshyApi - factory interface
 * @export
 */
export const MeshyApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MeshyApiFp(configuration)
    return {
        /**
         * Cancela una tarea de generación de modelo 3D. Marca la tarea como FAILED y detiene el procesamiento.
         * @summary Cancelar una tarea
         * @param {string} taskId ID único de la tarea (UUID)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meshyControllerCancelTask(taskId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.meshyControllerCancelTask(taskId, options).then((request) => request(axios, basePath));
        },
        /**
         * Inicia una nueva tarea para convertir una imagen en un modelo 3D usando Meshy.ai. Debes proporcionar una URL de imagen o una imagen en base64.
         * @summary Crear tarea de conversión de imagen a modelo 3D
         * @param {CreateImageTo3DDto} createImageTo3DDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meshyControllerCreateImageTo3DTask(createImageTo3DDto: CreateImageTo3DDto, options?: RawAxiosRequestConfig): AxiosPromise<CreateTaskResponseDto> {
            return localVarFp.meshyControllerCreateImageTo3DTask(createImageTo3DDto, options).then((request) => request(axios, basePath));
        },
        /**
         * Obtiene la URL de descarga del modelo generado en el formato especificado. La tarea debe estar completada (status: SUCCEEDED).
         * @summary Obtener URL de descarga del modelo
         * @param {string} taskId ID único de la tarea (UUID)
         * @param {MeshyControllerDownloadModelFormatEnum} [format] Formato del modelo a descargar
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meshyControllerDownloadModel(taskId: string, format?: MeshyControllerDownloadModelFormatEnum, options?: RawAxiosRequestConfig): AxiosPromise<DownloadModelResponseDto> {
            return localVarFp.meshyControllerDownloadModel(taskId, format, options).then((request) => request(axios, basePath));
        },
        /**
         * Obtiene una lista de todas las tareas de generación de modelos 3D creadas.
         * @summary Listar todas las tareas
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meshyControllerGetAllTasks(options?: RawAxiosRequestConfig): AxiosPromise<Array<TaskStatusResponseDto>> {
            return localVarFp.meshyControllerGetAllTasks(options).then((request) => request(axios, basePath));
        },
        /**
         * Obtiene el estado actual de una tarea de generación de modelo 3D desde la base de datos local (actualizada desde Meshy). Incluye el progreso, URLs de los modelos generados y cualquier error.
         * @summary Consultar estado de una tarea
         * @param {string} taskId ID único de la tarea (UUID local)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meshyControllerGetTaskStatus(taskId: string, options?: RawAxiosRequestConfig): AxiosPromise<TaskStatusResponseDto> {
            return localVarFp.meshyControllerGetTaskStatus(taskId, options).then((request) => request(axios, basePath));
        },
        /**
         * Obtiene el estado actual de una tarea directamente desde Meshy API, sin pasar por la base de datos local. Acepta tanto el taskId local (UUID) como el meshyTaskId (ID de Meshy). Si se proporciona un taskId local, se busca el meshyTaskId correspondiente en la BD.
         * @summary Consultar estado directamente desde Meshy
         * @param {string} taskIdOrMeshyId ID de la tarea local (UUID) o ID de Meshy. Si es un UUID local, se buscará el meshyTaskId correspondiente.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meshyControllerGetTaskStatusFromMeshy(taskIdOrMeshyId: string, options?: RawAxiosRequestConfig): AxiosPromise<TaskStatusResponseDto> {
            return localVarFp.meshyControllerGetTaskStatusFromMeshy(taskIdOrMeshyId, options).then((request) => request(axios, basePath));
        },
        /**
         * Descarga el modelo desde Meshy a través del servidor para evitar problemas de CORS. Devuelve el archivo directamente.
         * @summary Descargar modelo a través del servidor (proxy)
         * @param {string} taskId ID único de la tarea (UUID)
         * @param {MeshyControllerProxyModelFormatEnum} [format] Formato del modelo a descargar
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meshyControllerProxyModel(taskId: string, format?: MeshyControllerProxyModelFormatEnum, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.meshyControllerProxyModel(taskId, format, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MeshyApi - object-oriented interface
 * @export
 * @class MeshyApi
 * @extends {BaseAPI}
 */
export class MeshyApi extends BaseAPI {
    /**
     * Cancela una tarea de generación de modelo 3D. Marca la tarea como FAILED y detiene el procesamiento.
     * @summary Cancelar una tarea
     * @param {string} taskId ID único de la tarea (UUID)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MeshyApi
     */
    public meshyControllerCancelTask(taskId: string, options?: RawAxiosRequestConfig) {
        return MeshyApiFp(this.configuration).meshyControllerCancelTask(taskId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Inicia una nueva tarea para convertir una imagen en un modelo 3D usando Meshy.ai. Debes proporcionar una URL de imagen o una imagen en base64.
     * @summary Crear tarea de conversión de imagen a modelo 3D
     * @param {CreateImageTo3DDto} createImageTo3DDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MeshyApi
     */
    public meshyControllerCreateImageTo3DTask(createImageTo3DDto: CreateImageTo3DDto, options?: RawAxiosRequestConfig) {
        return MeshyApiFp(this.configuration).meshyControllerCreateImageTo3DTask(createImageTo3DDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Obtiene la URL de descarga del modelo generado en el formato especificado. La tarea debe estar completada (status: SUCCEEDED).
     * @summary Obtener URL de descarga del modelo
     * @param {string} taskId ID único de la tarea (UUID)
     * @param {MeshyControllerDownloadModelFormatEnum} [format] Formato del modelo a descargar
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MeshyApi
     */
    public meshyControllerDownloadModel(taskId: string, format?: MeshyControllerDownloadModelFormatEnum, options?: RawAxiosRequestConfig) {
        return MeshyApiFp(this.configuration).meshyControllerDownloadModel(taskId, format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Obtiene una lista de todas las tareas de generación de modelos 3D creadas.
     * @summary Listar todas las tareas
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MeshyApi
     */
    public meshyControllerGetAllTasks(options?: RawAxiosRequestConfig) {
        return MeshyApiFp(this.configuration).meshyControllerGetAllTasks(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Obtiene el estado actual de una tarea de generación de modelo 3D desde la base de datos local (actualizada desde Meshy). Incluye el progreso, URLs de los modelos generados y cualquier error.
     * @summary Consultar estado de una tarea
     * @param {string} taskId ID único de la tarea (UUID local)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MeshyApi
     */
    public meshyControllerGetTaskStatus(taskId: string, options?: RawAxiosRequestConfig) {
        return MeshyApiFp(this.configuration).meshyControllerGetTaskStatus(taskId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Obtiene el estado actual de una tarea directamente desde Meshy API, sin pasar por la base de datos local. Acepta tanto el taskId local (UUID) como el meshyTaskId (ID de Meshy). Si se proporciona un taskId local, se busca el meshyTaskId correspondiente en la BD.
     * @summary Consultar estado directamente desde Meshy
     * @param {string} taskIdOrMeshyId ID de la tarea local (UUID) o ID de Meshy. Si es un UUID local, se buscará el meshyTaskId correspondiente.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MeshyApi
     */
    public meshyControllerGetTaskStatusFromMeshy(taskIdOrMeshyId: string, options?: RawAxiosRequestConfig) {
        return MeshyApiFp(this.configuration).meshyControllerGetTaskStatusFromMeshy(taskIdOrMeshyId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Descarga el modelo desde Meshy a través del servidor para evitar problemas de CORS. Devuelve el archivo directamente.
     * @summary Descargar modelo a través del servidor (proxy)
     * @param {string} taskId ID único de la tarea (UUID)
     * @param {MeshyControllerProxyModelFormatEnum} [format] Formato del modelo a descargar
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MeshyApi
     */
    public meshyControllerProxyModel(taskId: string, format?: MeshyControllerProxyModelFormatEnum, options?: RawAxiosRequestConfig) {
        return MeshyApiFp(this.configuration).meshyControllerProxyModel(taskId, format, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const MeshyControllerDownloadModelFormatEnum = {
    Glb: 'glb',
    Fbx: 'fbx',
    Obj: 'obj',
    Usdz: 'usdz'
} as const;
export type MeshyControllerDownloadModelFormatEnum = typeof MeshyControllerDownloadModelFormatEnum[keyof typeof MeshyControllerDownloadModelFormatEnum];
/**
 * @export
 */
export const MeshyControllerProxyModelFormatEnum = {
    Glb: 'glb',
    Fbx: 'fbx',
    Obj: 'obj',
    Usdz: 'usdz'
} as const;
export type MeshyControllerProxyModelFormatEnum = typeof MeshyControllerProxyModelFormatEnum[keyof typeof MeshyControllerProxyModelFormatEnum];


